# Banco de pruebas del Hundir la flota.
Simplemente ignore, aqui hago atentados contra la humanidad y dudas a tutiplén


### Coso 0: Importar NumPy

In [14]:
import numpy as np

### Coso 1: Prueba acceso random matriz

In [15]:
matriz = np.full((10,20), 20)
matriz

array([[20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20]])

In [16]:
print(matriz[2,4])

20


### Coso 2: Vamos a mostrar caracter a caracter

In [17]:
matriz_vacia = np.full((10,10)," ")

#print(matriz_vacia[0:1])

matriz_vacia[5,8] = "a"

#print(matriz_vacia[0:1,0:-1])
matriz_vacia[0:1,:] = "*"
#print(matriz_vacia[0:1,:])


for i in range(matriz_vacia.shape[0]):
    for j in range(matriz_vacia.shape[1]):
        print(matriz_vacia[i,j],end=" ")
    print("")




* * * * * * * * * * 
                    
                    
                    
                    
                a   
                    
                    
                    
                    


### Coso 3: Accedemos al desgracia de una matriz


In [18]:
matriz = np.full((6,2), "*")
print(matriz)

print(" ")

for i in matriz:
    print(i)


[['*' '*']
 ['*' '*']
 ['*' '*']
 ['*' '*']
 ['*' '*']
 ['*' '*']]
 
['*' '*']
['*' '*']
['*' '*']
['*' '*']
['*' '*']
['*' '*']


In [19]:
barcos = np.full((6,4),"*")
barcos

array([['*', '*', '*', '*'],
       ['*', '*', '*', '*'],
       ['*', '*', '*', '*'],
       ['*', '*', '*', '*'],
       ['*', '*', '*', '*'],
       ['*', '*', '*', '*']], dtype='<U1')

In [20]:
array = np.array([[1,2],
                  [3,4],
                  [5,6],
                  [7,8]])
array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
print(array)
x = 0
array[x,0]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


np.int64(1)

In [22]:
epic_dict = {"Hola":34, "Adios":39}

epic_dict["Hola"]

34

In [23]:
array = np.full((10,10), 10)
array[9,9]

np.int64(10)

In [24]:
class Tablero():

    puntuacion_actual = 0
    casilla_inicial = "0"

    vidas_barcos = [4,3,3,2,2,2]
    
    
    barcos = np.full((6,2), "*")
    posiciones_barcos = []
    

    def __init__(self,tamano = 10):
        self.matriz = np.full((tamano, tamano), "-")

    def colocar_barco(self, contador):
        print("Contador =", contador)
        tablero = self.matriz.copy() # Aqui hacemos la copia del tablero para intentar colocar las casillas

        if (contador > len(self.vidas_barcos) -1):
            return
        
        sentido = np.random.randint(0,2)
        # 0 = horizontal
        # 1 = vertical
        numeroX = np.random.randint(0,10)
        numeroY = np.random.randint(0,10)

        if (self.matriz[numeroX, numeroY] == "O"):
            self.colocar_barco(contador)

        if (sentido == 1):
            bucle = True

            while bucle == True:
                if ((numeroX + self.vidas_barcos[contador]) > 9):
                    self.colocar_barco(contador)
                else:
                    for i in range(numeroX, numeroX + (self.vidas_barcos[contador])):
                        if ((numeroX + i) > 9 or tablero[numeroX + i][numeroY] == "O"):
                            self.colocar_barco(contador)
                        else:
                            tablero[numeroX + i][numeroY] = "O"
                            print("BUCLEO")
                    break

            self.posiciones_barcos.append([[numeroX,numeroY],[numeroX+self.vidas_barcos[contador],numeroY]])
            contador += 1
            self.matriz = tablero
            print(self.matriz)
            print()
            print("Nuevo -----")
            print()
            print("posicion_barcos:", self.posiciones_barcos)
            self.colocar_barco(contador)

        else: # Si es 0, el sentido es horizontal
            bucle = True
           
            while bucle == True:
                if ((numeroY + self.vidas_barcos[contador]) > 9):
                    self.colocar_barco(contador) # en caso de que no se pueda hacer reiniciamos la colocacion
                else:
                    for i in range(numeroY, numeroY + (self.vidas_barcos[contador])):
                        if ((numeroY + i) > 9 or tablero[numeroX][numeroY + i] == "O"):
                            self.colocar_barco(contador) # a reiniciar againn
                        else:
                            tablero[numeroX][numeroY + i] = "O"
                            print("BUCLEO")
                    bucle = False
            
            self.posiciones_barcos.append([[numeroX,numeroY],[numeroX+self.vidas_barcos[contador],numeroY]])
            contador += 1
            self.matriz = tablero
            print(self.matriz)
            print()
            print("Nuevo -----")
            print()
            print("posicion_barcos:", self.posiciones_barcos)
            self.colocar_barco(contador)


        print(self.matriz)

    def comprobar_puntuacion(self):
        if self.puntuacion_actual < 15:
            return 1
        else:
            return 0
        
            

    def disparar(self,casilla):
        letras = "ABCDEFGHIJ"
        indice_0 = letras.index(casilla[0])
        if(self.matriz[indice_0, casilla[1]] == "O"):
            self.matriz[indice_0, casilla[1]] = "X"
        else:
            self.matriz[indice_0, casilla[1]] = "A"

        self.comprobar_puntuacion([indice_0, casilla[1]], 0)

### Clase Tablero: Prueba 2 (checking exterior)

##### Funciona!

In [28]:
def crear_coordenadas(tamano):
    numeroX = np.random.randint(0,10)
    numeroY = np.random.randint(0,10)

    checking = True
    while checking == True:
        # print(numeroX,numeroY)
        if (numeroX > 8 or numeroY > 8):
            numeroX = np.random.randint(0,10)
            numeroY = np.random.randint(0,10)
        else:
            checking = False
            break

    return [numeroX, numeroY]


class Tablero():

    puntuacion_actual = 0
    casilla_inicial = "0"

    vidas_barcos = [4,3,3,2,2,2]
    
    
    barcos = np.full((6,2), "*")
    posiciones_barcos = []
    

    def __init__(self,tamano = 10):
        self.tamano = tamano
        self.matriz = np.full((tamano, tamano), "-")

    def colocar_barco(self, contador):
        # print("Contador =", contador)
        tablero = self.matriz.copy() # Aqui hacemos la copia del tablero para intentar colocar las casillas

        if (contador > len(self.vidas_barcos) -1):
            return
        
        sentido = np.random.randint(0,2)
        # 0 = derecha
        # 1 = abajo
        # 2 = izquierda
        # 3 = arriba
        # print("Sentido", sentido)
        numeros = crear_coordenadas(self.tamano)

        if (sentido == 1): # Vertical
            bucle_creacion = True
            while bucle_creacion == True:
                if (tablero[numeros[0], numeros[1]] == "O" or (numeros[0] + self.vidas_barcos[contador]) > 9):
                    numeros = crear_coordenadas(self.tamano)

                else:
                    for i in range(0, self.vidas_barcos[contador]):
                        if not (tablero[numeros[0] + i, numeros[1]] == "O" or (numeros[0] + i) > 9):
                            tablero[numeros[0] + i, numeros[1]] = "O"
                    break
        
            # print("Representacion: ")
            # print(tablero)
            contador += 1
            self.matriz = tablero
            self.colocar_barco(contador)

        else:
            bucle_creacion = True
            while bucle_creacion == True:
                if (tablero[numeros[0], numeros[1]] == "O" or (numeros[1] + self.vidas_barcos[contador]) > 9):
                    numeros = crear_coordenadas(self.tamano)
                else:
                    for i in range(0, self.vidas_barcos[contador]):
                        if not(tablero[numeros[0], numeros[1] + i] == "O" or (numeros[1] + i) > 9 ):
                            tablero[numeros[0], numeros[1] + i] = "O"
                    break
        
            # print("Representacion: ")
            # print(tablero)
            contador += 1
            self.matriz = tablero
            self.colocar_barco(contador)

    def comprobar_puntuacion(self):
        if self.puntuacion_actual < 15:
            return 1
        else:
            return 0
        
            

    def disparar(self,casilla):
        letras = "ABCDEFGHIJ"
        indice_0 = letras.index(casilla[0])
        if(self.matriz[indice_0, casilla[1]] == "O"):
            self.matriz[indice_0, casilla[1]] = "X"
        else:
            self.matriz[indice_0, casilla[1]] = "A"

        self.comprobar_puntuacion([indice_0, casilla[1]], 0)


tablero1 = Tablero(10)
tablero1.colocar_barco(0)

### Clase tablero 3: Ahora vamos a probar con muchas direcciones

In [29]:
def crear_coordenadas(tamano):
    numeroX = np.random.randint(0,10)
    numeroY = np.random.randint(0,10)

    checking = True
    while checking == True:
        # print(numeroX,numeroY)
        if (numeroX > 8 or numeroY > 8):
            numeroX = np.random.randint(0,10)
            numeroY = np.random.randint(0,10)
        else:
            checking = False
            break

    return [numeroX, numeroY]


class Tablero():

    puntuacion_actual = 0
    casilla_inicial = "0"

    vidas_barcos = [4,3,3,2,2,2]
    
    
    barcos = np.full((6,2), "*")
    posiciones_barcos = []
    

    def __init__(self,tamano = 10):
        self.tamano = tamano
        self.matriz = np.full((tamano, tamano), "-")

    def colocar_barco(self, contador):
        # print("Contador =", contador)
        tablero = self.matriz.copy() # Aqui hacemos la copia del tablero para intentar colocar las casillas

        if (contador > len(self.vidas_barcos) -1):
            return
        
        sentido = np.random.randint(0,4)
        
        # print("Sentido", sentido)
        numeros = crear_coordenadas(self.tamano)

        if (sentido == 1): # Vertical
            bucle_creacion = True
            while bucle_creacion == True:
                if (tablero[numeros[0], numeros[1]] == "O" or (numeros[0] + self.vidas_barcos[contador]) > 9):
                    numeros = crear_coordenadas(self.tamano)

                else:
                    for i in range(0, self.vidas_barcos[contador]):
                        if not (tablero[numeros[0] + i, numeros[1]] == "O" or (numeros[0] + i) > 9):
                            tablero[numeros[0] + i, numeros[1]] = "O"
                    break
        
            # print("Representacion: ")
            # print(tablero)
            contador += 1
            self.matriz = tablero
            self.colocar_barco(contador)

        else:
            bucle_creacion = True
            while bucle_creacion == True:
                if (tablero[numeros[0], numeros[1]] == "O" or (numeros[1] + self.vidas_barcos[contador]) > 9):
                    numeros = crear_coordenadas(self.tamano)
                else:
                    for i in range(0, self.vidas_barcos[contador]):
                        if not(tablero[numeros[0], numeros[1] + i] == "O" or (numeros[1] + i) > 9 ):
                            tablero[numeros[0], numeros[1] + i] = "O"
                    break

        # 0 = izquierda
        # 1 = derecha
        # 2 = arriba
        # 3 = abajo

        match (sentido): # tremendo switch -- Vamos a comprobar tambien el tema de los adyacentes
            case 0:
                bucle_creacion = True
                while bucle_creacion == True:
                    if (tablero[numeros[0], numeros[1]] == "O" or (numeros[1]- self.vidas_barcos[contador] < 0)):
                        numeros = crear_coordenadas(self.tamano)
                    else: 
                        for i in range(0, self.vidas_barcos[contador]):
                            if not (tablero[numeros[0], numeros[1] - i] == "O" or (numeros[1] + i) < 0):
                                tablero[numeros[0], numeros[1] - i] = "O"
                        break

            case 1:
                bucle_creacion = True
                while bucle_creacion == True:
                     if (tablero[numeros[0], numeros[1]] == "O" or (numeros[1]- self.vidas_barcos[contador] < 0)):
                         numeros = crear_coordenadas(self.tamano)
                     else: 
                         for i in range(0, self.vidas_barcos[contador]):
                             if not (tablero[numeros[0], numeros[1] + i] == "O" or (numeros[1] + i) < 0):
                                 tablero[numeros[0], numeros[1] - i] = "O"
                         break
                     
            case 2:
                pass
            case 3:
                pass
            case _:
                pass
        
            # print("Representacion: ")
            # print(tablero)
        contador += 1
        self.matriz = tablero
        self.colocar_barco(contador)

    def comprobar_puntuacion(self):
        if self.puntuacion_actual < 15:
            return 1
        else:
            return 0
        
            

    def disparar(self,casilla):
        letras = "ABCDEFGHIJ"
        indice_0 = letras.index(casilla[0])
        if(self.matriz[indice_0, casilla[1]] == "O"):
            self.matriz[indice_0, casilla[1]] = "X"
        else:
            self.matriz[indice_0, casilla[1]] = "A"

        self.comprobar_puntuacion([indice_0, casilla[1]], 0)


tablero1 = Tablero(10)
tablero1.colocar_barco(0)